### ISSUE TITLE
Do Pins disappear if the Items disappear from the Map?

### ISSUE THREAD

**Issue by himpich** [FelixReuthlinger/AutoMapPins#12]
If yes: Please add the information to the readme, would be helpful

If no: Please implement this option - so that ores & co get removed from the map, if they are picked up

Thanks :)

**Comment by FelixReuthlinger** [comment]
The pin is part of the object in game, so if the object does get destroyed, the pin will also get destroyed. For all objects like veins, etc. this is implemented and should work fine. If you try to pin something that does not follow game rules of destructible objects or pickable objects (like carrot seeds or berries) it might not work, since the game does not implement "destroying" or "picking" these.
