### ISSUE TITLE
[Suggestion] Lower Pin Discover Range

### ISSUE THREAD

**Issue by SaltSouls** [FelixReuthlinger/AutoMapPins#14]
It would be nice to have an option to lower the pin discovery range, seeing as how many pins appear outside of the normal discovered area. That or make it so that auto pins can't be placed when outside of the currently discovered areas.

**Comment by FelixReuthlinger** [comment]
Would be nice if this would work, but since the game does instantiate objects irrespectively of the discovery range, there is no simple way to implement this. I could add a range calculation similar I do in the https://github.com/FelixReuthlinger/DiscoveryRadius mod, but this will heavily impact performance. So, I guess, everyone would prefer to have a performant implementation over having a 100% realistic one. I got already quite some issues on performance, which cannot be improved, since it depends on how Valheim was built.
