### ISSUE TITLE
[Question] How To Mark Vegvisir?

### ISSUE THREAD

**Issue by Deadmano** [FelixReuthlinger/AutoMapPins#25]
I wasn't able to find a way to automatically mark Vegvisir sites, is there a way to do so? AFAIK they are just "special" runestones.

**Comment by FelixReuthlinger** [comment]
No, they are a different type of objects that I didn't implement patches for, yet.
Do you think they need a map mark? Since you usually just use them once to get the target marked on map.

**Comment by Deadmano** [comment]
> No, they are a different type of objects that I didn't implement patches for, yet. Do you think they need a map mark? Since you usually just use them once to get the target marked on map.

I think it'd be useful if an area is large (especially with modded dungeons that increase the size) to be able to pin-point one, and it works nicely when paired with HUDCompass.

**Comment by FelixReuthlinger** [comment]
I did have a look, unfortunately the game object type does not allow to use the usual awake-destroy unity cycle, so, I cannot add those to the mod. 
And anyways for pinning things inside dungeons, I would not recommend to do this, because it will be misleading to see all the pins on the ground, too.
Nevertheless, I just uploaded the new 2.0 version, with this version you can configure the maximum detection height in the .cfg file. If you set this to 10000 it might also detect things inside dungeon.
