### ISSUE TITLE
2.0 and beyond not working

### ISSUE THREAD

**Issue by billyknit** [FelixReuthlinger/AutoMapPins#27]
Sorry if I'm being dense, but I've deleted the mod, and both .cfg and .yaml files, then reinstalled.  None of the icons on the map match what configured before 2.0.

**Comment by Morpheus1101** [comment]
Try Uninstalling an re-installing the mod, then look in the overrides dir in the Config folder

**Comment by sfjuocekr** [comment]
The config file seems to have changed quite a bit, there are a lot of things missing now compared to older versions!

For example most of the Mistlands things are missing now as well, things like brains or the dungeons (Infested Mines).

You can manually add missing things from older config files, I feel like the pre-2.0 config had a more complete set of prefabs listed. But, it was also lacking other prefabs that later configs introduced.

**Comment by shnabors** [comment]
Same issues as commenters above.  I've been playing around with the .yaml files (copied old before update to compare with new) for quite awhile now and while I've been able to get some things back as they were before the Ashlands update, there are still a lot of things missing and a few buggy things.  For example, spawners in the swamp are now permanent.  Changed .yaml to false, but instead of deleting the spawner from map when I destroy it, it just changes color from red to white. Lots of other issues but too many to list.  Are we expected to recreate our own .yaml files from scratch?... or is this still a work in progress?

**Comment by billyknit** [comment]
I'm locking myself in at 1.3.1 I guess.  I was hoping to just upgrade (and even start over with the new configs) and have everything look the same (for example Troll Caves retaining their 1.3.1 look (like a cave, not a house after 2.0)) without me doing anything else.  I still have yet to test what Morph suggested in his comment above, but I doubt it will work, because as I said in my OP, I deleted everything and reinstalled and nothing changed.

**Comment by billyknit** [comment]
> Try Uninstalling an re-installing the mod, then look in the overrides dir in the Config folder

Completely uninstalled 1.3.1 (including removing yaml and cfg files beforehand), then installed 2.1.4.  No "overrides" dir is seen in the BepInEx\config folder.  Loading up the game results in the same as before... almost all pins (except portals and crypts) have turned into houses (ie. troll caves, morgan holes, etc).

**Comment by FelixReuthlinger** [comment]
> The config file seems to have changed quite a bit, there are a lot of things missing now compared to older versions!
> 
> For example most of the Mistlands things are missing now as well, things like brains or the dungeons (Infested Mines).
> 
> You can manually add missing things from older config files, I feel like the pre-2.0 config had a more complete set of prefabs listed. But, it was also lacking other prefabs that later configs introduced.

Yes, it might be that the default config lacks some things. This is due to that I do not play the game myself, also never played the Ashlands update running through Ashlands. I think I mentioned this in readme and notes that if someone tells me the missing things, I can also add them to the default configs.

**Comment by FelixReuthlinger** [comment]
> Same issues as commenters above. I've been playing around with the .yaml files (copied old before update to compare with new) for quite awhile now and while I've been able to get some things back as they were before the Ashlands update, there are still a lot of things missing and a few buggy things. For example, spawners in the swamp are now permanent. Changed .yaml to false, but instead of deleting the spawner from map when I destroy it, it just changes color from red to white. Lots of other issues but too many to list. Are we expected to recreate our own .yaml files from scratch?... or is this still a work in progress?

As mentioned in the other comment above, if you like to help me to get a more complete yaml to distribute to all, help if very welcome. As I don't play the game myself, I just ran through the game for a couple of hours to register all prefabs found, but might miss some and maybe not using optiomal settings.

The other thing with permanent option and changing it and then destroying something (and as you mentioned other issues) -> would be great if you can clearly tell what you did step wise to get to a buggy state. Otherwise hard for me to find all the things, since I am not actively playing myself right now :)

**Comment by FelixReuthlinger** [comment]
And one general comment regarding upgrading from v1.x to v2.x -> of course, since this is a major version change that is expected to break usage and features and config and ..., you maybe can start using the updated version right away, but previously having used an older version does not guarantee to be working - the major version change implies that things do break.

A workaround for all can be that you, of course, can delete all pins on your map, and then use the v2.x to create new ones. Upgrading existing game data from v1 to v2 is not something I can support you with.

**Comment by shnabors** [comment]
Hello Felix,
     I've fixed as much as I can but there are a few more things I need help with.  But first, as to your comment about upgrading from v1 to v2, the easiest solution is to uninstall the mod and delete the old configs and yaml files (this includes the files that accumulate in the cache, sometimes they can cause problems.)  Once you install v2 and run the game, a new yaml file is created and the old pins are removed from the map.  From there, shut down the game and edit the yaml file to your heart's content.  For example, I removed tin because its unnecessary and clutters the map (is active = false), added copper (is active = true) and removed carrots.
     Also, I learned the hard way that trying to merge items from v1 yaml to v2 yaml doesn't work because many of the prefabs have changed and the format for how you list items have changed.
     The new v2 yaml file is missing many items that were in v1.  For example, treasure chests, sunken karves, turnips in the swamp, and nothing is showing up in the plains (no tar pits, no barley or flax, no chests, no runes).  
     I would be happy to help you make a more complete default yaml.  However,I haven't revisited the Mistlands nor entered the Ashlands for my 1st time ( I started fresh with a new game, haven't gone that far yet) so I can't help with those biomes right now, but if you were to recreate a new default yaml and just make sure all the items you had in v1 were also in v2, that would be a great start.  
     Cheers,
          Scott

**Comment by FelixReuthlinger** [comment]
Please re-test the new 2.2.0 version :)
If you find anything not working, please open a new issue, I will close this for now
