### ISSUE TITLE
The ping that appears when someone joins the server stays permanently.

### ISSUE THREAD

**Issue by LepreSeanSD** [FelixReuthlinger/AutoMapPins#36]
![20240712223604_1](https://github.com/user-attachments/assets/ae85886c-1754-49dd-8055-40be8beb7440)

**Comment by FelixReuthlinger** [comment]
Hm that is weird, but I don't play and also not joined servers to test it. I will need to try to check what is going wrong there, since I also get the spawn pings but those go away in single player as I tried it so far.

**Comment by braaaaains** [comment]
I think I'm also having this problem, though I'm not completely sure where these yellow markers come from. Each time I start up the server though I see more of them and I can only delete them if I hit the exact right spot. They pile up quickly and I am unable to use the map without severe lag

**Comment by FelixReuthlinger** [comment]
the "yellow ping" pin is caused since the mod does interpret any markers on the map with the type "none", which is exactly the one used by the ping. This can be caused by markers that have been created with previous versions of the mod used (before v2.x). You can try to remove all markers (also previous, etc.) by using the console command "amp clear_pins". But be careful, since in multiplayer and with sharing and multiple characters, maybe all of them need to remove pins from previous versions. This can only be done by each client, since the pins on the map are stored in the player's profile.
