### ISSUE TITLE
Portals being marked with yellow pings even when set to false

### ISSUE THREAD

**Issue by braaaaains** [FelixReuthlinger/AutoMapPins#38]
Portals are being marked multiple times on the map with the yellow ping that shows when somebody shouts in multiplayer or spawns in, and they are being overlayed with the custom portal icon as well. I have them set to false in the config, but they are being marked anyway. This is causing an extreme FPS drop, I also cannot delete these markers so uninstalling does not seem to be fixing this

**Comment by FelixReuthlinger** [comment]
you should always be able to use the console command "amp clean..." to delete all markers btw

**Comment by FelixReuthlinger** [comment]
I don't know how or why this would happen that shouts or join pings would stay on the map. When I test the "/s asd" in single player the ping appears and just gets removed after it pinged a bit, like expected. Same as join markers "I have arrived!", it is visible as the ping pings, and get removed after the ping ended. 
I cannot test this on a server, since I do not have a server to test it and also not playing myself lately.
Can you share any config files you are using?

**Comment by braaaaains** [comment]
I don't think it's actually the shout ping, but it's the same icon that's used for that. It looks like these are being placed to represent portals, which we are placing and removing constantly. It places the same markers every time I start the game, so it overlaps the same markers from the last session. It isn't letting me attach the config, is there a way to do that?

**Comment by FelixReuthlinger** [comment]
I guess this might be similar to the other report https://github.com/FelixReuthlinger/AutoMapPins/issues/40
But I cannot reproduce it myself so far...
