### ISSUE TITLE
Can you add a distance config for discovering pins?

### ISSUE THREAD

**Issue by cCaptainn** [FelixReuthlinger/AutoMapPins#39]
The pins are discovered at the edge of the minimap radius, but I would like to be able to shorten the discovery radius. Is this possible?

**Comment by FelixReuthlinger** [comment]
discovery is shortened to the fog free range, you can try using mods that change the map discovery range, like the one I did https://thunderstore.io/c/valheim/p/FixItFelix/DiscoveryRadius/

**Comment by dTrigan** [comment]
I would also like to be able to reduce the detection radius, for example, so that the marks are displayed 15 meters away from the player even if the map is explored. Reduce the radius of detection of the map is not suitable because the marks will be displayed on the entire minicart without fog and to explore the map with 15 meters not suitable. Is it possible to add a setting for the radius of displaying marks around the player?
