### ISSUE TITLE
Custom additions to config not appearing in game

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#41]
I've added a heap of various Ores to the config an as far as i can tell its entered correctly, logoutput.log shows the vanilla file loads aok, but this does not..SO if you could perhaps shed some light to what im missing here please.  Changed it to a .txt instead of yml for purposes of github

[FixItFelix.AutoMapPins.categories.modded.txt](https://github.com/user-attachments/files/16647206/FixItFelix.AutoMapPins.categories.modded.txt)
[LogOutput.log](https://github.com/user-attachments/files/16647493/LogOutput.log)

**Comment by FelixReuthlinger** [comment]
If the mod does not print that it did find the file, then it did not find the file. Nothing about the file content being wrong, rather the naming, since it does look for files named like: 
https://github.com/FelixReuthlinger/AutoMapPins/blob/ccea6b7036c34035c6efd37906b35ecabea42fb7/Data/YamlFileStorage.cs#L35
https://github.com/FelixReuthlinger/AutoMapPins/blob/ccea6b7036c34035c6efd37906b35ecabea42fb7/Data/YamlFileStorage.cs#L73

Besides that some recommendations:

I see you are using permanent a lot, please consider using it less.
https://github.com/FelixReuthlinger/AutoMapPins/blob/ccea6b7036c34035c6efd37906b35ecabea42fb7/README.md?plain=1#L14 and following lines

And especially I would not use permanent and groupable together, since there is then no way to decide to remove a part of the pin (like if 3 items were found and you destroy one of them). But this is also kind of explained with the reamde line above that permanent pins need manual removal, no matter what.

**Comment by Morpheus1101** [comment]
In the config directory i even added those in the attached file into the vanilla cfg file and it still dosent pick them up an im sure the naming of them is correct.  I will remove the groupable an permanent though.  Guess i'll have to continue working to work out whats going on.

**Comment by FelixReuthlinger** [comment]
Idk, but maybe it is due to using r2... I am using TMM always, since r2 sometimes does screw up things.
The file and content of the file need to be found in the folder the game loads, those managers somehow copy around files sometimes. Maybe it does just not have the file in the right spot.

**Comment by Morpheus1101** [comment]
Most of the ores are added by a mod called BiomeFlora, iirc you need to use wackys to determine what ore spawns in what biome.

**Comment by Morpheus1101** [comment]
This works as intended in SinglePlayer, however dosent seem to function serverside. I do only have it loaded client side.

**Comment by FelixReuthlinger** [comment]
I cannot reproduce the behavior, sorry
