### ISSUE TITLE
Ping icons with and instead of map pins after logout and login (yeah, I saw reports but I want to share some details so I want to save them in one place)

### ISSUE THREAD

**Issue by Dorennor** [FelixReuthlinger/AutoMapPins#42]
Screenshot of my singleplayer map:

![зображення](https://github.com/user-attachments/assets/90cbcf43-a369-4738-a377-70b911e512d6)

Archive with my config:

[FixItFelix.AutoMapPins.categories.vanilla.zip](https://github.com/user-attachments/files/17180705/FixItFelix.AutoMapPins.categories.vanilla.zip)

Link to google disk with full Valheim archive (there are more mods), game saves, configs etc.:

[https://drive.google.com/drive/folders/1ip3XLv_4Qe17aW5P35JIg669s30tRzjx?usp=sharing](url)

It seems that there are some problems with loading of icons when you have some of them near. When you turning off grouping option (where it is possible) defect becomes no longer reproducible. But still remains in cases of pins which don't have that option (bosses spawners, runes, traders etc.). Also problem fixes when you disable isPermanent option.

**Comment by FelixReuthlinger** [comment]
well, this is similar to some other issues that were reported already. due to the requested freedom of being able to do a lot of wild things within the config you can also reach a level of configs that does not work very well. I cannot do much about this instead of reducing the freedom of being able to configure too many wild things.
