### ISSUE TITLE
This is awesome, can it be made compatible with ServerSideMap?

### ISSUE THREAD

**Issue by tgstyle** [FelixReuthlinger/AutoMapPins#5]
https://valheim.thunderstore.io/package/Mydayyy/ServerSideMap/

**Comment by FelixReuthlinger** [comment]
Nope, I doubt that this will make people happy, since ServerSideMap is meant to be used for infrequently created pins by humans. As far as I understand the author it will send over all pins to server and all players. If I would integrate this, it will impact players performance, since it will create many many many more pins than a human does create.
