### ISSUE TITLE
AMP filewatcher does not work

### ISSUE THREAD

**Issue by crolloS72** [FelixReuthlinger/AutoMapPins#6]
Hi. Lovely mod and beautiful symbols. The following is more a feedback to your cool work:

The filewatcher doesn't work for my dedicated server. I have to restart the server in order to make changes at the .yaml appear in game. Is there a command to reload the config file? 

I changed the configuration.vanilla.yaml in order to display some of the grouped markers in game. It was overwritten by your latest update. Do I have to rename the file to something else so that it will not happen again?

I suggest to add a possibility to adjust the range of detection in order to fit to the players map detection range? Atm its very large and also tracks uncharted territories.

I could'nt find an entry for autmapping the draugr villages or meadows villages. Is it possible to add them? You already added the village icon.

What do you think about to add icons32 to display not so important entries a bit smaller on the map? 

thanks a lot. Great Work!

![mapexample](https://github.com/FelixReuthlinger/AutoMapPins/assets/74319566/07fbb1d4-dd90-40b1-a004-176ce42952ec)

**Comment by FelixReuthlinger** [comment]
Thx for the feedback and ideas :) 

I changed something on the config syncing of pin configs, but not sure if this also will work in client-server setup, since I don't play on a server myself, maybe you can check if this improved with version 1.2.0.

About the icon sizes: I really don't know if it makes sense to use smaller icons, since then you will barely be able to identify them. Sometimes less is more, configuring less pins to be active and only the ones you really want might yield better user experience from my PoV.

About the villeages: there are config entries for them, you just need to edit and make active and make use of them. I think woodvillage / woodfarm / ... might be the one in meadows. I didn't default configure them, since I don't see too much use of it for myself, but feel free to use it in your configs.

About the detection range: well, this is very tricky, since the game does load prefabs as you approach them with a certain range, I cannot change this behavior in general. Adding custom functionality to not load until you approached and do see on the map the area would require very complex logic and maybe will then also impact more on performance.

**Comment by crolloS72** [comment]
I see. 

I suggested to vary the size for better clarity on the map since it's a pity  that these nice symbols (for example berries) never show up on the map for that reason. May be colored map pins do the job? :)

I figured out, that server sync is working fine. The cfg file has been transfered to client. 
Though when updating clientside from thunderstore FixItFelix.AutoMapPins.categories.vanilla.cfg will still be overwritten to your configuration. 
So if someone changed any entries from false to true, it has to be done again - or save the old cfg as backup.

**Comment by FelixReuthlinger** [comment]
But you do know that you can activate berries to show up, I just deactivated it per default, since too many icons just create a mess...

With server sync it does not matter what is written to the .cfg or .yaml file, since the sync will (should) load the values from server into memory (but will not write them back to the file). For checking if this works as expected you need to check the behavior in game rather than the file. Overwriting the file by download does also not matter, since server side configuration will overrule all coming from local file, if you set it up correctly.

**Comment by crolloS72** [comment]
I know how to activate/deactivate the icons on the map.

I tested server sync in the game. It worked fine. Server settings were used instead of clientside settings. In addition, the server has overwritten the clientside cfg file to its settings.

For clarity on the map, I wanted to suggest making the symbols colored or varying their size so that you can display berries, for example, without causing chaos on the map. At the moment the configurability of the cfg and the various icons offered are useless because they clutter up the map. 
I had to deactivate almost every non necessary icons to to maintain clarity. For that reason I reduced icons wich showing up on the map to very few like crypts, dungeons and caves at the moment.

Because it is an "auto" mappins mod, you do not have manual access to the symbols if you wanted to mark individual locations, for example, berries.
In my opinion, to ensure clarity, you have to design the symbols in a way that they can be displayed without causing chaos.

**Comment by FelixReuthlinger** [comment]
Imho there is no way to design icons so a user wanting to pin everything does not create chaos on the map :) You can choose how much and what you want by config, which is best option I can give to someone. Adding colors to pins will just let the chaos look like a rainbow.
